# Generated by Django 5.1.5 on 2025-10-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0002_location_date_added_location_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
