# Generated by Django 5.1.5 on 2025-10-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0003_alter_location_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_added',
            field=models.CharField(max_length=50),
        ),
    ]
