# Generated by Django 5.1.5 on 2025-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0004_alter_location_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sticker_img',
            field=models.ImageField(default='no_image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
