# Generated by Django 5.1.5 on 2025-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0006_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='country',
            new_name='name',
        ),
        migrations.AddField(
            model_name='countries',
            name='code',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
