# Generated by Django 5.2.7 on 2025-11-07 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0007_rename_country_countries_name_countries_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sticker_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
